// This file is auto-generated by FlutterFire CLI.
// Run: dart run flutterfire_configure
// Replace with your actual Firebase config.

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcapZ_Ur24GWuss8BiqzWJnnp7YxMBNw',
    appId: '1:796639195377:android:a571f23988e7146a9f7950',
    messagingSenderId: '796639195377',
    projectId: 'alexa-arts-classes',
    storageBucket: 'alexa-arts-classes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZcapZ_Ur24GWuss8BiqzWJnnp7YxMBNw',
    appId: '1:796639195377:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '796639195377',
    projectId: 'alexa-arts-classes',
    storageBucket: 'alexa-arts-classes.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}